//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermalis.VGMusicStudio.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kermalis.VGMusicStudio.Core.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} key.
        /// </summary>
        public static string ConfigKeySubkey {
            get {
                return ResourceManager.GetString("ConfigKeySubkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to stop playing the current playlist?.
        /// </summary>
        public static string EndPlaylistBody {
            get {
                return ResourceManager.GetString("EndPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command in track {0} at 0x{1:X}: 0x{2:X}.
        /// </summary>
        public static string ErrorAlphaDreamDSEMP2KSDATInvalidCommand {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamDSEMP2KSDATInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy invalid game code &quot;{0}&quot;.
        /// </summary>
        public static string ErrorAlphaDreamMP2KCopyInvalidGameCode {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KCopyInvalidGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game code &quot;{0}&quot; is missing..
        /// </summary>
        public static string ErrorAlphaDreamMP2KMissingGameCode {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KMissingGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing game code &quot;{0}&quot; in &quot;{1}&quot;{2}.
        /// </summary>
        public static string ErrorAlphaDreamMP2KParseGameCode {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KParseGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &quot;{0}&quot; has song {1} defined more than once between decimal and hexadecimal..
        /// </summary>
        public static string ErrorAlphaDreamMP2KSongRepeated {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KSongRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; count must be the same as &quot;{1}&quot; count..
        /// </summary>
        public static string ErrorAlphaDreamMP2KSongTableCounts {
            get {
                return ResourceManager.GetString("ErrorAlphaDreamMP2KSongTableCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be True or False..
        /// </summary>
        public static string ErrorBoolParse {
            get {
                return ResourceManager.GetString("ErrorBoolParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color {0} is not defined..
        /// </summary>
        public static string ErrorConfigColorMissing {
            get {
                return ResourceManager.GetString("ErrorConfigColorMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color {0} is defined more than once between decimal and hexadecimal..
        /// </summary>
        public static string ErrorConfigColorRepeated {
            get {
                return ResourceManager.GetString("ErrorConfigColorRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is invalid..
        /// </summary>
        public static string ErrorConfigKeyInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is missing..
        /// </summary>
        public static string ErrorConfigKeyMissing {
            get {
                return ResourceManager.GetString("ErrorConfigKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must have at least one entry..
        /// </summary>
        public static string ErrorConfigKeyNoEntries {
            get {
                return ResourceManager.GetString("ErrorConfigKeyNoEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown header version: 0x{0:X}.
        /// </summary>
        public static string ErrorDSEInvalidHeaderVersion {
            get {
                return ResourceManager.GetString("ErrorDSEInvalidHeaderVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key in track {0} at 0x{1:X}: {2}.
        /// </summary>
        public static string ErrorDSEInvalidKey {
            get {
                return ResourceManager.GetString("ErrorDSEInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no &quot;bgm(NNNN).smd&quot; files..
        /// </summary>
        public static string ErrorDSENoSequences {
            get {
                return ResourceManager.GetString("ErrorDSENoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Global Config.
        /// </summary>
        public static string ErrorGlobalConfig {
            get {
                return ResourceManager.GetString("ErrorGlobalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Song {0}.
        /// </summary>
        public static string ErrorLoadSong {
            get {
                return ResourceManager.GetString("ErrorLoadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid running status command in track {0} at 0x{1:X}: 0x{2:X}.
        /// </summary>
        public static string ErrorMP2KInvalidRunningStatusCommand {
            get {
                return ResourceManager.GetString("ErrorMP2KInvalidRunningStatusCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many nested call events in track {0}.
        /// </summary>
        public static string ErrorMP2KSDATNestedCalls {
            get {
                return ResourceManager.GetString("ErrorMP2KSDATNestedCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading GBA ROM (AlphaDream).
        /// </summary>
        public static string ErrorOpenAlphaDream {
            get {
                return ResourceManager.GetString("ErrorOpenAlphaDream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading DSE Folder.
        /// </summary>
        public static string ErrorOpenDSE {
            get {
                return ResourceManager.GetString("ErrorOpenDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading GBA ROM (MP2K).
        /// </summary>
        public static string ErrorOpenMP2K {
            get {
                return ResourceManager.GetString("ErrorOpenMP2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading SDAT File.
        /// </summary>
        public static string ErrorOpenSDAT {
            get {
                return ResourceManager.GetString("ErrorOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing &quot;{0}&quot;{1}.
        /// </summary>
        public static string ErrorParseConfig {
            get {
                return ResourceManager.GetString("ErrorParseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting DLS.
        /// </summary>
        public static string ErrorSaveDLS {
            get {
                return ResourceManager.GetString("ErrorSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting MIDI.
        /// </summary>
        public static string ErrorSaveMIDI {
            get {
                return ResourceManager.GetString("ErrorSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting SF2.
        /// </summary>
        public static string ErrorSaveSF2 {
            get {
                return ResourceManager.GetString("ErrorSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting WAV.
        /// </summary>
        public static string ErrorSaveWAV {
            get {
                return ResourceManager.GetString("ErrorSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This SDAT archive has no sequences..
        /// </summary>
        public static string ErrorSDATNoSequences {
            get {
                return ResourceManager.GetString("ErrorSDATNoSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not an integer value..
        /// </summary>
        public static string ErrorValueParse {
            get {
                return ResourceManager.GetString("ErrorValueParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; must be between {1} and {2}..
        /// </summary>
        public static string ErrorValueParseRanged {
            get {
                return ResourceManager.GetString("ErrorValueParseRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Advance binary (*.gba, *srl)|*.gba;*.srl|All files (*.*)|*.*.
        /// </summary>
        public static string FilterOpenGBA {
            get {
                return ResourceManager.GetString("FilterOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitro Soundmaker Sound Data (*.sdat)|*.sdat|All files (*.*)|*.*.
        /// </summary>
        public static string FilterOpenSDAT {
            get {
                return ResourceManager.GetString("FilterOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS Files (*.dls)|*.dls.
        /// </summary>
        public static string FilterSaveDLS {
            get {
                return ResourceManager.GetString("FilterSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Files (*.mid, *.midi)|*.mid;*.midi.
        /// </summary>
        public static string FilterSaveMIDI {
            get {
                return ResourceManager.GetString("FilterSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SF2 Files (*.sf2)|*.sf2.
        /// </summary>
        public static string FilterSaveSF2 {
            get {
                return ResourceManager.GetString("FilterSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV Files (*.wav)|*.wav.
        /// </summary>
        public static string FilterSaveWAV {
            get {
                return ResourceManager.GetString("FilterSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*).
        /// </summary>
        public static string GTKAllFiles {
            get {
                return ResourceManager.GetString("GTKAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Boy Advance binary (*.gba, *.srl).
        /// </summary>
        public static string GTKFilterOpenGBA {
            get {
                return ResourceManager.GetString("GTKFilterOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitro Soundmaker Sound Data (*.sdat).
        /// </summary>
        public static string GTKFilterOpenSDAT {
            get {
                return ResourceManager.GetString("GTKFilterOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLS Soundfont Files (*.dls).
        /// </summary>
        public static string GTKFilterSaveDLS {
            get {
                return ResourceManager.GetString("GTKFilterSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Sequence Files (*.mid, *.midi).
        /// </summary>
        public static string GTKFilterSaveMIDI {
            get {
                return ResourceManager.GetString("GTKFilterSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SF2 Soundfont Files (*.sf2).
        /// </summary>
        public static string GTKFilterSaveSF2 {
            get {
                return ResourceManager.GetString("GTKFilterSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Audio Data (*.wav).
        /// </summary>
        public static string GTKFilterSaveWAV {
            get {
                return ResourceManager.GetString("GTKFilterSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Current Playlist.
        /// </summary>
        public static string MenuEndPlaylist {
            get {
                return ResourceManager.GetString("MenuEndPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GBA ROM (AlphaDream).
        /// </summary>
        public static string MenuOpenAlphaDream {
            get {
                return ResourceManager.GetString("MenuOpenAlphaDream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DSE Folder.
        /// </summary>
        public static string MenuOpenDSE {
            get {
                return ResourceManager.GetString("MenuOpenDSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GBA ROM (MP2K).
        /// </summary>
        public static string MenuOpenMP2K {
            get {
                return ResourceManager.GetString("MenuOpenMP2K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SDAT File.
        /// </summary>
        public static string MenuOpenSDAT {
            get {
                return ResourceManager.GetString("MenuOpenSDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string MenuPlaylist {
            get {
                return ResourceManager.GetString("MenuPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VoiceTable as DLS.
        /// </summary>
        public static string MenuSaveDLS {
            get {
                return ResourceManager.GetString("MenuSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Song as MIDI.
        /// </summary>
        public static string MenuSaveMIDI {
            get {
                return ResourceManager.GetString("MenuSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VoiceTable as SF2.
        /// </summary>
        public static string MenuSaveSF2 {
            get {
                return ResourceManager.GetString("MenuSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Song as WAV.
        /// </summary>
        public static string MenuSaveWAV {
            get {
                return ResourceManager.GetString("MenuSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Song.
        /// </summary>
        public static string PlayerNextSong {
            get {
                return ResourceManager.GetString("PlayerNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string PlayerNotes {
            get {
                return ResourceManager.GetString("PlayerNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PlayerPause {
            get {
                return ResourceManager.GetString("PlayerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayerPlay {
            get {
                return ResourceManager.GetString("PlayerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PlayerPosition {
            get {
                return ResourceManager.GetString("PlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Song.
        /// </summary>
        public static string PlayerPreviousSong {
            get {
                return ResourceManager.GetString("PlayerPreviousSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        public static string PlayerRest {
            get {
                return ResourceManager.GetString("PlayerRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string PlayerStop {
            get {
                return ResourceManager.GetString("PlayerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        public static string PlayerTempo {
            get {
                return ResourceManager.GetString("PlayerTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PlayerType {
            get {
                return ResourceManager.GetString("PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpause.
        /// </summary>
        public static string PlayerUnpause {
            get {
                return ResourceManager.GetString("PlayerUnpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string PlaylistMusic {
            get {
                return ResourceManager.GetString("PlaylistMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play the following playlist?{0}.
        /// </summary>
        public static string PlayPlaylistBody {
            get {
                return ResourceManager.GetString("PlayPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs|0_0|song|1_1|songs|2_*|.
        /// </summary>
        public static string Song_s_ {
            get {
                return ResourceManager.GetString("Song(s)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceTable saved to {0}..
        /// </summary>
        public static string SuccessSaveDLS {
            get {
                return ResourceManager.GetString("SuccessSaveDLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI saved to {0}..
        /// </summary>
        public static string SuccessSaveMIDI {
            get {
                return ResourceManager.GetString("SuccessSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceTable saved to {0}..
        /// </summary>
        public static string SuccessSaveSF2 {
            get {
                return ResourceManager.GetString("SuccessSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV saved to {0}..
        /// </summary>
        public static string SuccessSaveWAV {
            get {
                return ResourceManager.GetString("SuccessSaveWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string TrackViewerArguments {
            get {
                return ResourceManager.GetString("TrackViewerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string TrackViewerEvent {
            get {
                return ResourceManager.GetString("TrackViewerEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string TrackViewerOffset {
            get {
                return ResourceManager.GetString("TrackViewerOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks.
        /// </summary>
        public static string TrackViewerTicks {
            get {
                return ResourceManager.GetString("TrackViewerTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Viewer.
        /// </summary>
        public static string TrackViewerTitle {
            get {
                return ResourceManager.GetString("TrackViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0}.
        /// </summary>
        public static string TrackViewerTrackX {
            get {
                return ResourceManager.GetString("TrackViewerTrackX", resourceCulture);
            }
        }
    }
}
