//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBAMusicStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GBAMusicStudio.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string AssemblerDefinition {
            get {
                return ResourceManager.GetString("AssemblerDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions cannot start with a digit..
        /// </summary>
        internal static string AssemblerErrorDefinitionDigit {
            get {
                return ResourceManager.GetString("AssemblerErrorDefinitionDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value: {0}.
        /// </summary>
        internal static string AssemblerErrorInvalidValue {
            get {
                return ResourceManager.GetString("AssemblerErrorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string AssemblerOpenFile {
            get {
                return ResourceManager.GetString("AssemblerOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Song.
        /// </summary>
        internal static string AssemblerPreviewSong {
            get {
                return ResourceManager.GetString("AssemblerPreviewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in bytes: {0}.
        /// </summary>
        internal static string AssemblerSizeInBytes {
            get {
                return ResourceManager.GetString("AssemblerSizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASM Assembler.
        /// </summary>
        internal static string AssemblerTitle {
            get {
                return ResourceManager.GetString("AssemblerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string AssemblerValue {
            get {
                return ResourceManager.GetString("AssemblerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting MIDI files to this game engine is not supported at this time..
        /// </summary>
        internal static string ErrorEngineOpenMIDI {
            get {
                return ResourceManager.GetString("ErrorEngineOpenMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to ASM from this game engine is not supported at this time..
        /// </summary>
        internal static string ErrorEngineSaveASM {
            get {
                return ResourceManager.GetString("ErrorEngineSaveASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to MIDI from this game engine is not supported at this time..
        /// </summary>
        internal static string ErrorEngineSaveMIDI {
            get {
                return ResourceManager.GetString("ErrorEngineSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Song {0}.
        /// </summary>
        internal static string ErrorLoadSong {
            get {
                return ResourceManager.GetString("ErrorLoadSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song has no tracks..
        /// </summary>
        internal static string ErrorNoTracks {
            get {
                return ResourceManager.GetString("ErrorNoTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading ROM.
        /// </summary>
        internal static string ErrorOpenGBA {
            get {
                return ResourceManager.GetString("ErrorOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting ASM.
        /// </summary>
        internal static string ErrorSaveASM {
            get {
                return ResourceManager.GetString("ErrorSaveASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting MIDI.
        /// </summary>
        internal static string ErrorSaveMIDI {
            get {
                return ResourceManager.GetString("ErrorSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Exporting SF2 File.
        /// </summary>
        internal static string ErrorSaveSF2 {
            get {
                return ResourceManager.GetString("ErrorSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song has too many tracks ({0})..
        /// </summary>
        internal static string ErrorTooManyTracks {
            get {
                return ResourceManager.GetString("ErrorTooManyTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASM files.
        /// </summary>
        internal static string FilterOpenASM {
            get {
                return ResourceManager.GetString("FilterOpenASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBA files.
        /// </summary>
        internal static string FilterOpenGBA {
            get {
                return ResourceManager.GetString("FilterOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI files.
        /// </summary>
        internal static string FilterOpenMIDI {
            get {
                return ResourceManager.GetString("FilterOpenMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASM file.
        /// </summary>
        internal static string FilterSaveASM {
            get {
                return ResourceManager.GetString("FilterSaveASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI file.
        /// </summary>
        internal static string FilterSaveMIDI {
            get {
                return ResourceManager.GetString("FilterSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SF2 file.
        /// </summary>
        internal static string FilterSaveSF2 {
            get {
                return ResourceManager.GetString("FilterSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string MenuData {
            get {
                return ResourceManager.GetString("MenuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ASM.
        /// </summary>
        internal static string MenuOpenASM {
            get {
                return ResourceManager.GetString("MenuOpenASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MIDI.
        /// </summary>
        internal static string MenuOpenMIDI {
            get {
                return ResourceManager.GetString("MenuOpenMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ROM.
        /// </summary>
        internal static string MenuOpenROM {
            get {
                return ResourceManager.GetString("MenuOpenROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Config.
        /// </summary>
        internal static string MenuRefreshConfig {
            get {
                return ResourceManager.GetString("MenuRefreshConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Song To ASM.
        /// </summary>
        internal static string MenuSaveASM {
            get {
                return ResourceManager.GetString("MenuSaveASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Song To MIDI.
        /// </summary>
        internal static string MenuSaveMIDI {
            get {
                return ResourceManager.GetString("MenuSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export VoiceTable To SF2.
        /// </summary>
        internal static string MenuSaveSF2 {
            get {
                return ResourceManager.GetString("MenuSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Editor.
        /// </summary>
        internal static string MenuTrackEditor {
            get {
                return ResourceManager.GetString("MenuTrackEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceTable Editor.
        /// </summary>
        internal static string MenuVoiceTableEditor {
            get {
                return ResourceManager.GetString("MenuVoiceTableEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error converting the MIDI file:{0}.
        /// </summary>
        internal static string MIDIConverterError {
            get {
                return ResourceManager.GetString("MIDIConverterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MIDI.
        /// </summary>
        internal static string MIDIConverterOpenFile {
            get {
                return ResourceManager.GetString("MIDIConverterOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Song.
        /// </summary>
        internal static string MIDIConverterPreviewSong {
            get {
                return ResourceManager.GetString("MIDIConverterPreviewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI Converter.
        /// </summary>
        internal static string MIDIConverterTitle {
            get {
                return ResourceManager.GetString("MIDIConverterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Converting MIDI.
        /// </summary>
        internal static string MIDIConverterTitleError {
            get {
                return ResourceManager.GetString("MIDIConverterTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C;C#;D;D#;E;F;F#;G;G#;A;A#;B.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string PlayerDelay {
            get {
                return ResourceManager.GetString("PlayerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string PlayerNotes {
            get {
                return ResourceManager.GetString("PlayerNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PlayerPause {
            get {
                return ResourceManager.GetString("PlayerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string PlayerPlay {
            get {
                return ResourceManager.GetString("PlayerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string PlayerPosition {
            get {
                return ResourceManager.GetString("PlayerPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string PlayerStop {
            get {
                return ResourceManager.GetString("PlayerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string PlayerTempo {
            get {
                return ResourceManager.GetString("PlayerTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string PlayerType {
            get {
                return ResourceManager.GetString("PlayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpause.
        /// </summary>
        internal static string PlayerUnpause {
            get {
                return ResourceManager.GetString("PlayerUnpause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play the following playlist?{0}.
        /// </summary>
        internal static string PlayPlaylistBody {
            get {
                return ResourceManager.GetString("PlayPlaylistBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Playlist.
        /// </summary>
        internal static string PlayPlaylistTitle {
            get {
                return ResourceManager.GetString("PlayPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASM saved to {0}..
        /// </summary>
        internal static string SuccessSaveASM {
            get {
                return ResourceManager.GetString("SuccessSaveASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI saved to {0}..
        /// </summary>
        internal static string SuccessSaveMIDI {
            get {
                return ResourceManager.GetString("SuccessSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceTable saved to {0}..
        /// </summary>
        internal static string SuccessSaveSF2 {
            get {
                return ResourceManager.GetString("SuccessSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Assembling File.
        /// </summary>
        internal static string TitleAssemblerError {
            get {
                return ResourceManager.GetString("TitleAssemblerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ASM.
        /// </summary>
        internal static string TitleOpenASM {
            get {
                return ResourceManager.GetString("TitleOpenASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GBA ROM.
        /// </summary>
        internal static string TitleOpenGBA {
            get {
                return ResourceManager.GetString("TitleOpenGBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MIDI.
        /// </summary>
        internal static string TitleOpenMIDI {
            get {
                return ResourceManager.GetString("TitleOpenMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export ASM File.
        /// </summary>
        internal static string TitleSaveASM {
            get {
                return ResourceManager.GetString("TitleSaveASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export MIDI File.
        /// </summary>
        internal static string TitleSaveMIDI {
            get {
                return ResourceManager.GetString("TitleSaveMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export SF2 File.
        /// </summary>
        internal static string TitleSaveSF2 {
            get {
                return ResourceManager.GetString("TitleSaveSF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Event.
        /// </summary>
        internal static string TrackEditorAddEvent {
            get {
                return ResourceManager.GetString("TrackEditorAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string TrackEditorArguments {
            get {
                return ResourceManager.GetString("TrackEditorArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arg. {0}.
        /// </summary>
        internal static string TrackEditorArgX {
            get {
                return ResourceManager.GetString("TrackEditorArgX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Voices.
        /// </summary>
        internal static string TrackEditorChangeVoices {
            get {
                return ResourceManager.GetString("TrackEditorChangeVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string TrackEditorEvent {
            get {
                return ResourceManager.GetString("TrackEditorEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string TrackEditorFrom {
            get {
                return ResourceManager.GetString("TrackEditorFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string TrackEditorOffset {
            get {
                return ResourceManager.GetString("TrackEditorOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Event.
        /// </summary>
        internal static string TrackEditorRemoveEvent {
            get {
                return ResourceManager.GetString("TrackEditorRemoveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks.
        /// </summary>
        internal static string TrackEditorTicks {
            get {
                return ResourceManager.GetString("TrackEditorTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Editor.
        /// </summary>
        internal static string TrackEditorTitle {
            get {
                return ResourceManager.GetString("TrackEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string TrackEditorTo {
            get {
                return ResourceManager.GetString("TrackEditorTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0}.
        /// </summary>
        internal static string TrackEditorTrackX {
            get {
                return ResourceManager.GetString("TrackEditorTrackX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string VoiceTableEditorAddress {
            get {
                return ResourceManager.GetString("VoiceTableEditorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceTable Editor.
        /// </summary>
        internal static string VoiceTableEditorTitle {
            get {
                return ResourceManager.GetString("VoiceTableEditorTitle", resourceCulture);
            }
        }
    }
}
